language: go
go:
  - "1.11.2"
sudo: required
services:
  - docker
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get -u github.com/axw/gocov/gocov github.com/mattn/goveralls github.com/tcnksm/ghr
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.11.2

script:
  - $GOPATH/bin/golangci-lint run --deadline 3m
  - cd $TRAVIS_BUILD_DIR && go test -i && ./test_compile.sh
  - goveralls -coverprofile=coverage.out -service travis-ci
after_success:
  - ./deploy.sh
